name: Test JMeter on GitHub Action
on:
  workflow_dispatch:
    inputs:
      virtual_user:
        required: true
        description: 'Enter virtual user count'
        default: '10'
      ramp_up_time:
        required: true
        description: 'Enter ramp up time'
        default: '10'
      loop_count:
        required: true
        description: 'Enter loop count'
        default: '10'
jobs:
  run_jmeter_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run JMeter Action on a Test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: /PerformanceScript.jmx
          outputReportsFolder: ./reports/
          args: "-Juser_count=${{ github.event.inputs.virtual_user }} -Jramp_up_time=${{ github.event.inputs.ramp_up_time }} -Jloop_count=${{ github.event.inputs.loop_count }}"

      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: reports/
