- name: Create reports directory
  run: mkdir reports

- name: JMeter Test
  uses: QAInsights/PerfAction@v5.6.2
  with:
    test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
    args: "-e -o ./reports/html/"
    
- name: Upload Results
  uses: actions/upload-artifact@v3
  with:
    name: jmeter-results
    path: result.jtl
    if-no-files-found: error

- name: Upload HTML Reports
  uses: actions/upload-artifact@v3
  with:
    name: jmeter-html-reports
    path: reports
    if-no-files-found: error           

 - name: PerfAction for JMeter
  # You may pin to the exact commit or the version.
  # uses: QAInsights/PerfAction@5a3c503bff845dd019d4b6e30d71f4585494a2ea
  uses: QAInsights/PerfAction@v5.6.2
  with:
    # JMeter test plan to execute
    test-plan-path: example_demo.jmx
  
